### ISSUE TITLE
MTi-10 driver problem

### ISSUE THREAD

**Issue by katsumoto185** [ethz-asl/ethzasl_xsens_driver#11]
Hi,

I plugged mti10 my computer, ubuntu 12.04, ros groovy.  I run rosrun xsens_driver mtdevice.py.

firstly run output is : 
invalid checksum; discarding data and waiting for next message.
MT error: Ack (0x31) expected, MID 0x32 received instead (after 10 tries).

secondly and others run output is: 

akay@akay:~/Desktop/xsens_mt-pre3.5$ rosrun xsens_driver mtdevice.py 
MT error 0x04: Invalid message.MT error: timeout waiting for message.

whats my fault?

thanks.

**Comment by fcolas** [comment]
This should be solve since a while, and is obsolete with all recent changes.
If it happens again with the new version, please open a new issue.
