### ISSUE TITLE
cannot launch node of type [xsens_driver/mtnode.py]

### ISSUE THREAD

**Issue by anthogd** [ethz-asl/ethzasl_xsens_driver#110]
Dear All,

I am using an xsens MTi10 and I want to log data on ROS.
I am using ros melodic and ubuntu 18.

Here is my problem:
I use roscore and open another terminal to clone this driver and then I roslaunch the x_sens_driver.launch in order to get the nodes to publish the different topics. However, when I do that, I get the following error
`
ERROR: cannot launch node of type [xsens_driver/mtnode.py]: xsens_driver
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share
`
I am fairly new to ROS and I would like to know if I have forgotten anything before doing a roslaunch.
Any help is appreciated. Many Thanks!

**Comment by patlican23** [comment]
Hi, did you solve this issue?
