### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by peci1** [ethz-asl/ethzasl_xsens_driver#25]
It's been a year since the last version... What about releasing a new one? :)

**Comment by fcolas** [comment]
I'm working on a more complete support of mk. 4 devices. It makes sense do a release at that time.

**Comment by fcolas** [comment]
Can you test the new branch: better_mark_iv_support
It's supposed to be compatible with both old and new devices in both legacy and new mode (and you can configure in either mode).

**Comment by fcolas** [comment]
Done in 27f44f7

**Comment by peci1** [comment]
Thanks, we've deployed version 2 on the robot, fixed a few lines of (our) code, and it works.
