### ISSUE TITLE
Publish_time_ref in mtnode.py has error

### ISSUE THREAD

**Issue by Jebediah** [ethz-asl/ethzasl_xsens_driver#29]
TimeReference message member is named time_ref.
http://docs.ros.org/api/sensor_msgs/html/msg/TimeReference.html
There are two lines that refer to time_ref_msg.time
Works after changing to time_ref_msg.time_ref

**Comment by fcolas** [comment]
Thanks for the report. It's fixed in bdcd6cf16bf53f6cf39f1f15c3f6163c8313ee3a.
