### ISSUE TITLE
ROS wiki page has outdated usage of mtdevice.py

### ISSUE THREAD

**Issue by herr-biber** [ethz-asl/ethzasl_xsens_driver#30]
http://wiki.ros.org/xsens_driver#mtdevice.py contains the documentation of ```mtdevice.py```. However, it is outdated and does not match the [upstream usage](https://github.com/ethz-asl/ethzasl_xsens_driver/blob/master/nodes/mtdevice.py#L1150) anymore.

Can you please update the ROS wiki page?

Cheers

**Comment by fcolas** [comment]
Indeed, thanks.
I'll do that when I can edit the wiki again.

**Comment by fcolas** [comment]
It's done.
