### ISSUE TITLE
Crash when running in ros kinetic

### ISSUE THREAD

**Issue by Andersw88** [ethz-asl/ethzasl_xsens_driver#38]
> Traceback (most recent call last):
>   File "/opt/ros/kinetic/lib/xsens_driver/mtnode.py", line 717, in <module>
>     main()
>   File "/opt/ros/kinetic/lib/xsens_driver/mtnode.py", line 713, in main
>     driver.spin()
>   File "/opt/ros/kinetic/lib/xsens_driver/mtnode.py", line 122, in spin
>     self.spin_once()
>   File "/opt/ros/kinetic/lib/xsens_driver/mtnode.py", line 684, in spin_once
>     if self.pub_analog_in1_pub is None:
> AttributeError: 'XSensDriver' object has no attribute 'pub_analog_in1_pub'

pub_analog_in1_pub, typo with pub both in front and back?

Update:
Made a pull request with the typo fixed, "analog_in1_pub" seem to be the intended name considering the next line in the code and it seem to work.

**Comment by fcolas** [comment]
Yes, indeed. Many thanks.
