### ISSUE TITLE
Driver outputs running measurements in the terminal

### ISSUE THREAD

**Issue by raymond30031** [ethz-asl/ethzasl_xsens_driver#53]
Hello Francis,

With the latest changes, the driver starts to output measurements in the terminal.
I assume it was not intentional.

the print statements are at line 596 and 597 of mynode.py

**Comment by fcolas** [comment]
Hi, indeed, sorry for that. It's solved in 0ab8073f76481d22a2a325d90d9dd7be67ee07ca
