### ISSUE TITLE
New at all

### ISSUE THREAD

**Issue by JorgeHormaza** [ethz-asl/ethzasl_xsens_driver#59]
Hi there, 

My name is Jorge and I'm totally new in ROS. I've been working with python for a while and I want to get the real-time data from one or two MTw Xsens for a project of my Uni. First, I tried to use the API from Xsens with python but Python is unsupported platform by Xsens so I couldn't. After I found this repository and I guess I can get the real-time data with it but I've never used ROS. 
 
So then, I want to know how to use this repository step by step with ROS and Python. I already read the Package Summary in WikiROS but it's not clear for me.

How can I load the package and the CMakeList in ROS?
How can I run the python code with ROS?

sorry because I know that probably for you those are stupid questions?

**Comment by fcolas** [comment]
Hi Jorge,
The issues here are more about specific problems you encounter with the driver.
If you want help to begin using ROS, the best is really to check the documentation and do the tutorials [1]. Once you've taken a look at ROS, if you still have ROS questions, you can try to ask them to ROS answers [2].
Finally, if this Xsens driver malfunctions or if the documentation is unclear, you can come back here and open a specific issue.
In the meantime, I'll close this issue as off-topic.

[1] http://wiki.ros.org/
[2] https://answers.ros.org/questions/
