### ISSUE TITLE
Driver adheres to REP 105?

### ISSUE THREAD

**Issue by juliangaal** [ethz-asl/ethzasl_xsens_driver#62]
Hi, 
I'm using [robot localization](http://docs.ros.org/kinetic/api/robot_localization/html/index.html) and was wondering if the drier follows [REP 105](http://www.ros.org/reps/rep-0105.html) standards, in particular, can I assume 

> all heading data to start with its zero point facing east?

found in [robot_localization docs](http://docs.ros.org/kinetic/api/robot_localization/html/integrating_gps.html#imu-data)

Thanks

**Comment by fcolas** [comment]
Sorry for the delay. Yes, I'm using the standard ROS conventions for reference frames.
