### ISSUE TITLE
Configuration parameteres mti-3 1-series

### ISSUE THREAD

**Issue by matteopantano** [ethz-asl/ethzasl_xsens_driver#63]
Hey guys,

I am struggling with the configuration of a mti-3. I would like to know if I can tell to the xsens to activate representative motion and ICC otherwise the reading is not consistent. Furthermore I would like to deactivate AHS.

Thanks

**Comment by fcolas** [comment]
These are new features I didn't know existed. It seems to have been introduced sometimes last year, maybe along with mk5 devices.
I'll try to take a quick look but if not too many things changed, it could be relatively quick to add.

**Comment by fcolas** [comment]
I've started to code the features for this support, but I don't have access to a fifth generation device to test it.
Could you take a look at the `support_gen_5` branch and test it, please?
The new features are mainly the `--gnss-platform`, `--option_flags`, and `--icc-command` command line arguments to `mtdevice.py`. Obviously you cannot really test the first one, but you should be able to play around with the other two, especially to activate representative motion and ICC and to toggle AHS.

**Comment by fcolas** [comment]
@matteopantano Any news? It'd be great if you could help me test the functionality you requested.

**Comment by fcolas** [comment]
@matteopantano Ping?

**Comment by fcolas** [comment]
I've merged the branch.
