### ISSUE TITLE
How to use imu_filter_madgwick

### ISSUE THREAD

**Issue by matteopantano** [ethz-asl/ethzasl_xsens_driver#64]
Hi,

Is there a way to use IMU filter madgwick with xsens_driver?

Thanks.

**Comment by fcolas** [comment]
I don't know this package but from a quick look at the documentation I don't see why not (using a small remapping of the topics). But that's a question more for the maintainer of this package. You can also try asking it on [answers.ros.org](answers.ros.org).

**Comment by matteopantano** [comment]
I did that but the filter return me nan values, if I try to use another IMU (aka phidgets spatial) it runs smoothly. This was the reason of my question regarding this package. Thanks anyway
