### ISSUE TITLE
Package compatibility with MTi-1 Series 3D Module

### ISSUE THREAD

**Issue by danendrasingh** [ethz-asl/ethzasl_xsens_driver#68]
Hello 
Is this package compatible with MTi-1 Series 3D Module, Link below:

https://www.digikey.com/product-detail/en/xsens-technologies-bv/MTI-3-DK/MTI-3-DK-ND/5325385

**Comment by fcolas** [comment]
I have no experience but that development kit is supposed to allow you an easier access to the device, in particular through USB (or serial) connection. Therefore I don't see why it shouldn't work.
Several people have posted issues on MT-1 series devices; I wouldn't be surprised if they actually used the DK. You might try to contact them; or even directly Xsens if you want to be sure.
