### ISSUE TITLE
Suggest adding an initial wait to allow the sensor to come online

### ISSUE THREAD

**Issue by shahvi** [ethz-asl/ethzasl_xsens_driver#72]
Hi,
A small enhancement suggestion.  For applications where the IMU might be on a relay, I suggest adding a parameter to specify a small wait time before the node attempts connection to the serial port.  This would allow the IMU to be online before the node attempts any config.
Thanks.

**Comment by fcolas** [comment]
@shahvi I've implemented an `initial_wait` in #79 so as to help for #42. Could you check whether it is enough for your issue too?

**Comment by shahvi** [comment]
This is great, will try it out in the next few days.
