### ISSUE TITLE
Synchronization setting allows for negative numbers but driver code does not?

### ISSUE THREAD

**Issue by chutsu** [ethz-asl/ethzasl_xsens_driver#81]
The Xsens IMU allows one to offset the synchronization setting with a negative offset (doc [here](https://github.com/ethz-asl/ethzasl_xsens_driver/blob/master/nodes/mtdevice.py#L1279)):

```
Synchronization settings:
    The format follows the xsens protocol documentation. All fields are required
    and separated by commas.
    Note: The entire synchronization buffer is wiped every time a new one
          is set, so it is necessary to specify the settings of multiple
          lines at once.
...

        Offset:
            Offset from event to pulse generation.
            100 microseconds unit, range [-30000...+30000]
```

The `struct.pack()` format code in `data = b''.join(struct.pack('!BBBBHHHH', *sync_setting)` of:
```
def SetSyncSettings(self, sync_settings):
        """Set the synchronisation settings (mark IV)"""
        self._ensure_config_state()
        data = b''.join(struct.pack('!BBBBHHHH', *sync_setting)
                        for sync_setting in sync_settings)
        self.write_ack(MID.SetSyncSettings, data)
```
in [Line 342 of `mtdevice.py`](https://github.com/ethz-asl/ethzasl_xsens_driver/blob/master/nodes/mtdevice.py#L342). Should the last element not be `h` and not `H` to allow for a negative number? (format code doc [here](https://docs.python.org/2/library/struct.html#format-characters))

**Comment by fcolas** [comment]
Ah, good catch.
Actually it's more subtle than that as it depends whether it's a Delay, Clock period, or Offset value. All three can go at that eighth spot (and I realize that the command line documentation is not clear on that) but they behave differently:
- Delay is unsigned in 100us units between 0 and 60000,
- Clock period is in 1ms units (probably signed but it's not specified),
- Offset is signed in 100us units between -30000 and 30000.
This can be differentiated based on both the function and synchronization line (or maybe just the sync line, it might seem).

I'll have to add a bit of logic here. Thanks for spotting this.
