### ISSUE TITLE
Does this driver support PPS for Mti-300?

### ISSUE THREAD

**Issue by maxvalor** [ethz-asl/ethzasl_xsens_driver#90]
Does this driver support PPS for Mti-300?

**Comment by fcolas** [comment]
@maxvalor What is PPS? A quick glance through the documentation raised only synchronization through GNSS (MTi-7 or MTi-G-710).

**Comment by snakehaihai** [comment]
isn't the pps should be from external device connection? like   Arduino connect to both IMU and LIDAR by PPS.

For Mti-300 it should be SyncIn Pin 7 Blue  +GND Pin 2 Yellow-green  
For Ouster 64. its the 6pin connector thing in the box.  one at the bottom left and one at middle left.
Connect both to Arduino pin 13 and GND.  
Dada, hello there,  there you have it

**Comment by fcolas** [comment]
Doesn't seem to be related to the node. Closing.
