### ISSUE TITLE
Error message 0x04: The message is invalid or not implemented

### ISSUE THREAD

**Issue by gustavorv** [ethz-asl/ethzasl_xsens_driver#95]
Hi! I've been trying to change the configurations of my MTi-G for a while by using the following command `./mtdevice.py --configure="pp"` so that I can get the ECEF coordinates but i always get the same error message. I tried to include some others( like 'ad' and 'wd' for example ) as it's described on the driver but I still get the same message. On the other hand when I change the legacy configurations, everything works out fine. Am I unable to normally change the configurations because mine is a legacy product or am I doing something wrong? Thanks in advance for the help!

**Comment by fcolas** [comment]
The MTi-G is indeed a “legacy” product and you have to stick to the mark iii protocol.
