### ISSUE TITLE
Fatal: could not find proper MT device

### ISSUE THREAD

**Issue by guan4286** [ethz-asl/ethzasl_xsens_driver#96]
g@g:~/tutorial_ws$ lsusb 
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 0424:5744 Standard Microsystems Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 008: ID 17ef:6019 Lenovo 
Bus 001 Device 007: ID 2639:0003 Xsens MTi-30 AHRS
Bus 001 Device 002: ID 04d9:1836 Holtek Semiconductor, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
g@g:~/tutorial_ws$ sudo chmod 777 /dev/bus/usb/00
001/ 002/ 003/ 004/ 
g@g:~/tutorial_ws$ sudo chmod 777 /dev/bus/usb/001/00
001  002  007  008  
g@g:~/tutorial_ws$ sudo chmod 777 /dev/bus/usb/001/007 
[sudo] password for g: 
g@g:~/tutorial_ws$ roslaunch xsens_driver xsens_driver.launch 
... logging to /home/g/.ros/log/fc0b3f14-1ef0-11e9-bf2f-2cfda1bc2526/roslaunch-g-2755.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://g:43823/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /xsens_driver/angular_velocity_covariance_diagonal: [0.0004, 0.0004, ...
 * /xsens_driver/baudrate: 0
 * /xsens_driver/device: auto
 * /xsens_driver/frame_id: /imu
 * /xsens_driver/frame_local: ENU
 * /xsens_driver/initial_wait: 0.1
 * /xsens_driver/linear_acceleration_covariance_diagonal: [0.0004, 0.0004, ...
 * /xsens_driver/no_rotation_duration: 0
 * /xsens_driver/orientation_covariance_diagonal: [0.01745, 0.01745...
 * /xsens_driver/timeout: 0.002

NODES
  /
    xsens_driver (xsens_driver/mtnode.py)

ROS_MASTER_URI=http://localhost:11311

process[xsens_driver-1]: started with pid [2772]
[INFO] [1548235684.744982]: Found parameter: ~device, value: auto
[INFO] [1548235684.746848]: Found parameter: ~baudrate, value: 0
[INFO] [1548235684.749052]: Found parameter: ~timeout, value: 0.002
[INFO] [1548235684.751343]: Found parameter: ~initial_wait, value: 0.1
[ERROR] [1548235690.174063]: Fatal: could not find proper MT device.
[xsens_driver-1] process has finished cleanly
log file: /home/g/.ros/log/fc0b3f14-1ef0-11e9-bf2f-2cfda1bc2526/xsens_driver-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by pedrobagatin** [comment]
> how to solve it?

Did you fix? Got same problem...

**Comment by guan4286** [comment]
yes i already fix it






At 2019-04-03 12:21:34, "Pedro Bagatin" <notifications@github.com> wrote:


how to solve it?

Did you fix? Got same problem...

**Comment by guan4286** [comment]
sudo chmod 777 /dev/bus/usb/00

**Comment by mlauret** [comment]
Hello, 

I think you should add a udev rules to be less error prone when managing multiple USB on your PC.
Here is a document to do it : https://doc.ubuntu-fr.org/udev

The udev rules consist of a  file in /etc/udev/rules.d (in ubuntu) that manage plugged devices (USB/Serial/SD/etc.) when loading a driver.

In the case of the Xsens, the rules.d should look like this : 

`BUS=="usb", ATTRS{idVendor}=="2639", ATTRS{idProduct}=="0003",  MODE="0666", SYMLINK+="xsens_mti"`

Also, you can take a look at this repo : https://github.com/xsens/xsens_mti_ros_node#troubleshooting

The troubleshooting guide as answers to manage the access right on the MT Devices (with Udev rules or Group)

**Comment by G-KUMAR** [comment]
Is there some permanent solution to this problem??
Getting the error:
`Fatal: could not find proper MT device.` with MTi-30 on `roslaunch xsens_driver xsens_driver.launch`
Device is showing on running `lsusb`.  Tried `sudo chmod 777 /dev/bus/usb/00` but the error still persists.
Changing the USB port on the computer works sometimes but its random every time I restart the system.  Sometimes it does not work on any of the USB ports.

**Comment by fcolas** [comment]
@G-KUMAR It is an issue with your configuration. See the comment from @mlauret above.
